### ISSUE TITLE
Thank you + Extra Info

### ISSUE THREAD

**Issue by maurcarvalho** [chmccue/ui-python-robotframework-pageobject-examples#1]
Hello @chmccue, how are you doing?

First of all, thank you so much to share this knowledge here on github, I really appreciate your atitute.
So, I've been looking for some test framework who offer a way to create a stable architecture and easy to insert new test cases. i.e from QA Engineers without programming background. That's when I found Robot, and I've been very excited about it since then, so, could you share with my your experience building your test project based on this framework?
- What's the pros/cons?
- Do you recommend it?
- Do you think the way you did on this project (structure/files/architecture at all) is a production ready setup?

If you have any extra material or architecture scaffold to share with me It will be awesome.
By the way, I'm using the official documentation to make my setup but your project fit very well with what I need, I mean, a bootstrap to grow with. Do you have any considerations about it?

Thank you again,
Mauricio Carvalho

**Comment by chmccue** [comment]
Hello,

First off, let me apologize for not replying to your note for nearly 8 years, I somehow did not see it until now, when I happened to be looking through some of my old repositories and making some minor adjustments to the readme of this one. I know this reply is very long overdue and no longer helpful, and great to see that it looks like you have accomplished some greater things in your repository since. Wanted to also say I am very glad to hear that someone benefited from learning with this repository back in 2015. To answer your questions anyway (better late than never, right?):

* What's the pros/cons?
Nearly 8 years later, I have not worked with Robot Framework for nearly 5 years now, however I still think it's a great framework and has excellent documentation on how to use things with it. It really helped me in the past with learning and gaining confidence in test automation, when I was not as strong with Python and Java. Plus in my opinion, the built-in reports are excellent. It provides so much out of the box. If I could think of a con for it, I would say that it's not used as often at many companies as something like pure Java or Python with Selenium/Cucumber, etc. Therefore if looking for jobs that use it, it may be more difficult.

* Do you recommend it?
 I would certainly recommend it to someone that may not have a lot of knowledge or experience with programming languages like Java or Python yet would like to learn how to automate tests and grow their knowledge. It is a very useful framework that has many available libraries, plus if you do happen to know Python, you can expand it with your own custom libraries that can be used with Robot Framework. You may also be able to extend it with Java, if I recall correctly.

* Do you think the way you did on this project (structure/files/architecture at all) is a production ready setup?
If I had to structure the framework in this repository again today, I would definitely make some architectural changes and organize it more to my preferences based on my experiences up to today, such as:
  - creating a step folder to separate the page object files from the step files (in this repository, they are essentially combined in the pages folder).
  - make the test files less technical and more readable with Gherkin.
  - replace most of the xpath locators, as I don't like using xpath anymore, unless absolutely nothing else will work.

But I would certainly say the structure of the project could work in a production ready setup, as for a time it was used in that setup.

Best of luck to you!
